# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-12 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='./media/default.jpg', upload_to=b''),
        ),
    ]
